tuning-trouble:main.c
	gcc -g -O0 -o $@ $<

clean:
	rm tuning-trouble

test:tuning-trouble
	./tuning-trouble test0.txt	
	./tuning-trouble test1.txt	
	./tuning-trouble test2.txt	
	./tuning-trouble test3.txt	
	./tuning-trouble test4.txt	
